version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "Harsha@51" | docker login -u "harshakastala" --password-stdin
  build:
    commands:
      - echo "Building the Docker image..."  
      - docker build -t harshakastala/samplenode:latest .
  post_build:
    commands:
      - echo "Pushing Docker image to DockerHub..."
      - docker push harshakastala/samplenode:latest
      
      
artifacts:
  files:
    - '**/*'
