version: 0.2

env:
  variables:
    IMAGE_TAG: "1.0"

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  build:
    commands:
      - sed -i "s/{VERSION}/$IMAGE_TAG/g" Dockerfile
      - docker build -t harshakastala/samplenode:$IMAGE_TAG .
      - export IMAGE_TAG=$(echo $IMAGE_TAG | awk -F. '{$NF++;print $0}')
      - echo "IMAGE_TAG=$IMAGE_TAG" >> output_artifacts.txt

artifacts:
  files:
    - output_artifacts.txt

