version: 0.2
phases:
    pre_build:
      commands:
        - echo "Logging in to Docker Hub..."
        - echo "Harsha@51" | docker login -u "harshakastala" --password-stdin
    build:
      commands:
        - echo "Building the Docker image..."
        - docker build -t harshakastala/samplenode:latest .
        - echo "Pushing the Docker image..."
        - docker push harshakastala/samplenode:latest
artifacts:
  files:
    - '**/*'
