version: 0.2
env:
  variables:
    DOCKERHUB_USERNAME: harshakastala
    DOCKERHUB_PASSWORD: Harsha@51
    DOCKERHUB_REPO: harshakastala/samplenode
    ECS_CLUSTER: mycluster
    ECS_SERVICE: myservice
phases:
  pre_build:
    commands:
      - echo Logging in to Dockerhub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $DOCKERHUB_REPO .
      - docker tag $DOCKERHUB_REPO:latest $DOCKERHUB_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Pushing Docker image to Dockerhub...
      - docker push $DOCKERHUB_REPO:latest
      - docker push $DOCKERHUB_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Updating ECS service...
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
artifacts:
  files: imagedefinitions.json
